export const bugBountyCourses = [
  {
    id: "xss",
    title: "Cross-Site Scripting (XSS)",
    description: "Complete guide to finding and exploiting XSS vulnerabilities in modern web applications.",
    image: "/images/courses/xss.png",
    level: "Beginner to Advanced",
    category: "Web",
  },
  {
    id: "sqli",
    title: "SQL Injection",
    description: "From basic to advanced SQL Injection techniques, bypasses and real-world exploitation.",
    image: "/images/courses/sqli.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "xxe",
    title: "XML External Entity (XXE)",
    description: "Deep dive into XXE attacks, out-of-band techniques and modern bypasses.",
    image: "/images/courses/xxe.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "ssrf",
    title: "Server-Side Request Forgery (SSRF)",
    description: "SSRF exploitation, cloud metadata attacks and advanced bypass methods.",
    image: "/images/courses/ssrf.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "idor",
    title: "Insecure Direct Object Reference (IDOR)",
    description: "Finding and exploiting IDOR vulnerabilities in APIs and web applications.",
    image: "/images/courses/idor.png",
    level: "Beginner",
    category: "Web",
  },
  {
    id: "auth-bypass",
    title: "Authentication Bypass",
    description: "Common authentication flaws, JWT attacks and session management issues.",
    image: "/images/courses/auth.png",
    level: "Intermediate",
    category: "Web",
  },
  {
    id: "rce",
    title: "Remote Code Execution (RCE)",
    description: "From command injection to full RCE chains in real bug bounty targets.",
    image: "/images/courses/rce.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "api-security",
    title: "API Security Testing",
    description: "REST & GraphQL API vulnerabilities, mass assignment, BOLA and more.",
    image: "/images/courses/api.png",
    level: "Intermediate",
    category: "API",
  },
  {
    id: "business-logic",
    title: "Business Logic Flaws",
    description: "Finding logic bugs that scanners miss – race conditions, price manipulation etc.",
    image: "/images/courses/logic.png",
    level: "Advanced",
    category: "Web",
  },
  {
    id: "file-upload",
    title: "File Upload Vulnerabilities",
    description: "Bypassing file upload restrictions and achieving RCE through uploads.",
    image: "/images/courses/upload.png",
    level: "Intermediate",
    category: "Web",
  },
];