services:

  backend:
    build: ./backend
    container_name: khan-baba-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: khan-baba-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend