// Saare flags sirf backend pe rahenge (frontend me kabhi nahi)
const FLAGS = {
  // ========== WEB ==========
  web: {
    xss: {
      1: "KHANSPLOIT{REFLECTED_XSS_01}",
      2: "KHANSPLOIT{DOM_HASH_XSS_02}",
      3: "KHANSPLOIT{STORED_XSS_03}",
      4: "KHANSPLOIT{BLIND_XSS_04}",
      5: "KHANSPLOIT{FILTER_BYPASS_05}",
    },
    sqli: {
      1: "KHANSPLOIT{SQLI_AUTH_BYPASS_01}",
      2: "KHANSPLOIT{SQLI_UNION_02}",
      3: "KHANSPLOIT{SQLI_ERROR_03}",
      4: "KHANSPLOIT{SQLI_BLIND_04}",
      5: "KHANSPLOIT{SQLI_FILTER_05}",
    },
    xxe: {
      1: "KHANSPLOIT{XXE_BASIC_01}",
      2: "KHANSPLOIT{XXE_FILE_02}",
      3: "KHANSPLOIT{XXE_SSRF_03}",
      4: "KHANSPLOIT{XXE_BLIND_04}",
      5: "KHANSPLOIT{XXE_FILTER_05}",
    },
    ssrf: {
      1: "KHANSPLOIT{SSRF_BASIC_01}",
      2: "KHANSPLOIT{SSRF_INTERNAL_02}",
      3: "KHANSPLOIT{SSRF_CLOUD_03}",
      4: "KHANSPLOIT{SSRF_PROTOCOL_04}",
      5: "KHANSPLOIT{SSRF_FILTER_05}",
    },
    idor: {
      1: "KHANSPLOIT{IDOR_BASIC_01}",
      2: "KHANSPLOIT{IDOR_HORIZONTAL_02}",
      3: "KHANSPLOIT{IDOR_VERTICAL_03}",
      4: "KHANSPLOIT{IDOR_API_04}",
      5: "KHANSPLOIT{IDOR_BLIND_05}",
    },
    csrf: {
      1: "KHANSPLOIT{CSRF_BASIC_01}",
      2: "KHANSPLOIT{CSRF_GET_02}",
      3: "KHANSPLOIT{CSRF_TOKEN_BYPASS_03}",
      4: "KHANSPLOIT{CSRF_JSON_04}",
      5: "KHANSPLOIT{CSRF_LOGIN_05}",
    },
    fileupload: {
      1: "KHANSPLOIT{FILE_UPLOAD_BASIC_01}",
      2: "KHANSPLOIT{FILE_UPLOAD_BLACKLIST_02}",
      3: "KHANSPLOIT{FILE_UPLOAD_MIME_03}",
      4: "KHANSPLOIT{FILE_UPLOAD_NULL_04}",
      5: "KHANSPLOIT{FILE_UPLOAD_ADVANCED_05}",
    },
  },

  // ========== CLOUD ==========
  cloud: {
    aws: {
      1: "KHANSPLOIT{AWS_S3_PUBLIC_01}",
      2: "KHANSPLOIT{AWS_IAM_PRIVESC_02}",
      3: "KHANSPLOIT{AWS_METADATA_SSRF_03}",
      4: "KHANSPLOIT{AWS_SG_OPEN_04}",
      5: "KHANSPLOIT{AWS_LAMBDA_SECRETS_05}",
    },
    azure: {
      1: "KHANSPLOIT{AZURE_BLOB_PUBLIC_01}",
      2: "KHANSPLOIT{AZURE_AAD_PRIVESC_02}",
      3: "KHANSPLOIT{AZURE_IMDS_03}",
      4: "KHANSPLOIT{AZURE_NSG_OPEN_04}",
      5: "KHANSPLOIT{AZURE_KEYVAULT_05}",
    },
    gcp: {
      1: "KHANSPLOIT{GCP_GCS_PUBLIC_01}",
      2: "KHANSPLOIT{GCP_IAM_PRIVESC_02}",
      3: "KHANSPLOIT{GCP_METADATA_03}",
      4: "KHANSPLOIT{GCP_FIREWALL_OPEN_04}",
      5: "KHANSPLOIT{GCP_SECRETMANAGER_05}",
    },
  },

  // ========== MOBILE ==========
  mobile: {
    android: {
      1: "KHANSPLOIT{ANDROID_STORAGE_01}",
      2: "KHANSPLOIT{ANDROID_EXPORTED_02}",
      3: "KHANSPLOIT{ANDROID_NETWORK_03}",
      4: "KHANSPLOIT{ANDROID_HARDCODED_04}",
      5: "KHANSPLOIT{ANDROID_DEEPLINK_05}",
    },
    ios: {
      1: "KHANSPLOIT{IOS_STORAGE_01}",
      2: "KHANSPLOIT{IOS_JAILBREAK_02}",
      3: "KHANSPLOIT{IOS_DEEPLINK_03}",
      4: "KHANSPLOIT{IOS_HARDCODED_04}",
      5: "KHANSPLOIT{IOS_BINARY_05}",
    },
    apk: {
      1: "KHANSPLOIT{APK_DECOMPILE_01}",
      2: "KHANSPLOIT{APK_SECRETS_02}",
      3: "KHANSPLOIT{APK_MANIFEST_03}",
      4: "KHANSPLOIT{APK_SIGNING_04}",
      5: "KHANSPLOIT{APK_ROOTBYPASS_05}",
    },
  },

  // ========== AI ==========
  ai: {
    "prompt-injection": {
      1: "KHANSPLOIT{PROMPT_INJECTION_BASIC_01}",
      2: "KHANSPLOIT{PROMPT_INJECTION_IGNORE_02}",
      3: "KHANSPLOIT{PROMPT_INJECTION_ROLEPLAY_03}",
      4: "KHANSPLOIT{PROMPT_INJECTION_ENCODING_04}",
      5: "KHANSPLOIT{PROMPT_INJECTION_ADVANCED_05}",
    },
    "llm-jailbreak": {
      1: "KHANSPLOIT{LLM_JAILBREAK_BASIC_01}",
      2: "KHANSPLOIT{LLM_JAILBREAK_POLICY_02}",
      3: "KHANSPLOIT{LLM_JAILBREAK_CHARACTER_03}",
      4: "KHANSPLOIT{LLM_JAILBREAK_MULTILAYER_04}",
      5: "KHANSPLOIT{LLM_JAILBREAK_MAXSEC_05}",
    },
    "rag-security": {
      1: "KHANSPLOIT{RAG_LEAKAGE_01}",
      2: "KHANSPLOIT{RAG_INDIRECT_INJECTION_02}",
      3: "KHANSPLOIT{RAG_POISONING_03}",
      4: "KHANSPLOIT{RAG_CONTEXT_EXTRACT_04}",
      5: "KHANSPLOIT{RAG_MULTIDOC_05}",
    },
    "customer-support": {
    1: "KHANSPLOIT{CS_BASIC_INJECTION_01}",
    2: "KHANSPLOIT{CS_IGNORE_INSTRUCTIONS_02}",
    3: "KHANSPLOIT{CS_ROLEPLAY_ADMIN_03}",
    4: "KHANSPLOIT{CS_DATA_EXTRACTION_04}",
    5: "KHANSPLOIT{CS_ADVANCED_JAILBREAK_05}",
  },

  "system-prompt-leak": {
  1: "KHANSPLOIT{SYSTEM_PROMPT_LEAK_01}",
  2: "KHANSPLOIT{SYSTEM_PROMPT_LEAK_02}",
  3: "KHANSPLOIT{SYSTEM_PROMPT_LEAK_03}",
  4: "KHANSPLOIT{SYSTEM_PROMPT_LEAK_04}",
  5: "KHANSPLOIT{SYSTEM_PROMPT_LEAK_05}",
},
  "indirect-injection": {
  1: "KHANSPLOIT{INDIRECT_INJECTION_01}",
  2: "KHANSPLOIT{INDIRECT_INJECTION_02}",
  3: "KHANSPLOIT{INDIRECT_INJECTION_03}",
  4: "KHANSPLOIT{INDIRECT_INJECTION_04}",
  5: "KHANSPLOIT{INDIRECT_INJECTION_05}",
},
"tool-abuse": {
  1: "KHANSPLOIT{TOOL_ABUSE_01}",
  2: "KHANSPLOIT{TOOL_ABUSE_02}",
  3: "KHANSPLOIT{TOOL_ABUSE_03}",
  4: "KHANSPLOIT{TOOL_ABUSE_04}",
  5: "KHANSPLOIT{TOOL_ABUSE_05}",
},
"multi-turn-jailbreak": {
  1: "KHANSPLOIT{MULTI_TURN_01}",
  2: "KHANSPLOIT{MULTI_TURN_02}",
  3: "KHANSPLOIT{MULTI_TURN_03}",
  4: "KHANSPLOIT{MULTI_TURN_04}",
  5: "KHANSPLOIT{MULTI_TURN_05}",
},
"guardrail-bypass": {
  1: "KHANSPLOIT{GUARDRAIL_BYPASS_01}",
  2: "KHANSPLOIT{GUARDRAIL_BYPASS_02}",
  3: "KHANSPLOIT{GUARDRAIL_BYPASS_03}",
  4: "KHANSPLOIT{GUARDRAIL_BYPASS_04}",
  5: "KHANSPLOIT{GUARDRAIL_BYPASS_05}",
},






  },

// ===== REDTEAM =======//

redteam: {
  "web-redteam": {
    1: "KHANSPLOIT{WEB_RECON_01}",
    2: "KHANSPLOIT{WEB_AUTH_BYPASS_02}",
    3: "KHANSPLOIT{WEB_IDOR_03}",
    4: "KHANSPLOIT{WEB_FILE_UPLOAD_04}",
    5: "KHANSPLOIT{WEB_RCE_SIM_05}",
  },
  "network-pentesting": {
    1: "KHANSPLOIT{NET_SCAN_01}",
    2: "KHANSPLOIT{NET_SERVICE_02}",
    3: "KHANSPLOIT{NET_SMB_03}",
    4: "KHANSPLOIT{NET_LATERAL_04}",
    5: "KHANSPLOIT{NET_PIVOT_05}",
  },
  "system-hacking": {
    1: "KHANSPLOIT{SYS_ENUM_01}",
    2: "KHANSPLOIT{SYS_WEAK_PASS_02}",
    3: "KHANSPLOIT{SYS_SUDO_03}",
    4: "KHANSPLOIT{SYS_CRON_04}",
    5: "KHANSPLOIT{SYS_ROOT_05}",
  },
  "social-engineering": {
    1: "KHANSPLOIT{SE_PHISH_01}",
    2: "KHANSPLOIT{SE_PRETEXT_02}",
    3: "KHANSPLOIT{SE_VISHING_03}",
    4: "KHANSPLOIT{SE_USB_04}",
    5: "KHANSPLOIT{SE_FULL_05}",
  },
  "reverse-engineering": {
    1: "KHANSPLOIT{RE_STRINGS_01}",
    2: "KHANSPLOIT{RE_STATIC_02}",
    3: "KHANSPLOIT{RE_LOGIC_03}",
    4: "KHANSPLOIT{RE_PACKER_04}",
    5: "KHANSPLOIT{RE_FULL_05}",
  },
},




};

function getFlag(category, lab, level) {
  try {
    return FLAGS[category][lab][level] || null;
  } catch {
    return null;
  }
}

module.exports = { FLAGS, getFlag }